In [36]:
# 自定义层
## 不带参数的层

In [37]:
import torch
import torch.nn.functional as F
from torch import nn


class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [38]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [39]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

In [40]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(-3.9581e-09, grad_fn=<MeanBackward0>)

## 带参数的层
以上我们知道了如何定义简单的层，下面我们继续定义具有参数的层， 这些参数可以通过训练进行调整。 我们可以使用内置函数来创建参数，这些函数提供一些基本的管理功能。 比如管理访问、初始化、共享、保存和加载模型参数。 这样做的好处之一是：我们不需要为每个自定义层编写自定义的序列化程序。

现在，让我们实现自定义版本的全连接层。 回想一下，该层需要两个参数，一个用于表示权重，另一个用于表示偏置项。 在此实现中，我们使用修正线性单元作为激活函数。 该层需要输入参数：in_units和units，分别表示输入数和输出数。

In [41]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [42]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.3097, -0.4868, -0.0848],
        [ 0.0975, -0.8379,  0.6717],
        [-0.9206,  0.4796,  0.0721],
        [ 1.5796, -0.8147, -2.5280],
        [-1.3433,  0.4285,  0.7453]], requires_grad=True)

In [43]:
linear(torch.rand(2, 5))

tensor([[0.2646, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])

In [44]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[0.],
        [0.]])